### ISSUE TITLE
Regarding environment variable in MWDust code.....

### ISSUE THREAD

**Issue by rupakroy** [jobovy/mwdust#6]
Dear all,
I am Rupak Roy a researcher in Astronomy, and interested to run the code MWDust. However, getting problem while installing. It will be nice if someone can help me in this regard. The detail is as given below : 
I am using Python 2.7.13 :: Anaconda custom (64-bit).
Suppose my mwdust directory is at /home/rroy/Software/MWdust/mwdust-1.0
I made a directory at /home/rroy/Software/MWdust/DUST_DIR
I added this line in the .bashrc file in my home directory  :  export DUST_DIR="/home/rroy/Software/MWdust/DUST_DIR"
I sourced .bashrc and changed the directory to /home/rroy/Software/MWdust/mwdust-1.0
I ran the command : python setup.py install
I got the following python error :
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    'maps')])
  File "/home/rroy/Software/ANACONDA/anaconda2/lib/python2.7/subprocess.py", line 181, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/rroy/Software/ANACONDA/anaconda2/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/rroy/Software/ANACONDA/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/rroy/Software/ANACONDA/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

I checked that before giving the error, the code generated an empty directory /home/rroy/Software/MWdust/DUST_DIR/maps

Looking forward for the suggestions..

Kind regards
Rupak Roy

**Comment by jobovy** [comment]
I think this may be related to your not installing using `sudo`. I've checked in a possible fixed, please download the latest version and try again.
